---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_solo

platforms:
- name: centos-5.11
- name: centos-6.6
- name: centos-7.1
- name: debian-6.0.10
- name: debian-7.8
- name: ubuntu-10.04
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: ubuntu-14.10
- name: fedora-19
  driver_config:
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-19_chef-provisionerless.box
- name: fedora-20

suites:
- name: default
  run_list: recipe[swap_tuning_test]
- name: oldchef
  provisioner:
    require_chef_omnibus: 11.10.4
  run_list: recipe[swap_tuning_test]
- name: newchef
  provisioner:
    require_chef_omnibus: 11.12.0
  run_list: recipe[swap_tuning_test]
